version: "3"
services:
  api:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    env_file:
      - .env
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${database_password}
      POSTGRES_DB: ${database_name}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
